export const types = {
  USER_LOGIN: "USER_LOGIN",
  GET_ALL_POSTS: "GET_ALL_POSTS",
  CREATE_POST: "CREATE_POST",
  DELETE_POST: "DELETE_POST",
  GET_ONE_POST: "GET_ONE_POST",
  UPDATE_POST: "UPDATE_POST",
  USER_UPLOAD_PICTURE: "USER_UPLOAD_PICTURE",
};
