<?php

namespace app\models;

use dektrium\user\helpers\Password;
use Yii;
use yii\helpers\ArrayHelper;
use dektrium\user\models\User as BaseUser;
use yii\web\ForbiddenHttpException;

/**
 * @property string  $tel_id
 * @property string  $tel_username
 * @property integer $vk_id
 * @property string  $vk_auth_key
 * @property string  $access_token
 */


class User extends BaseUser
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = parent::rules();
        $rules[] =  [['tel_username'], 'string', 'max' => 255];
        $rules[] =  [['tel_id'], 'integer'];
        $rules[] =  [['vk_id'], 'integer'];
        $rules[] =  [['vk_auth_key', 'access_token'], 'string', 'max' => 255];
        $rules[] =  [['vk_id', 'vk_auth_key', 'access_token'], 'safe'];
        return $rules;
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
//        return self::findOne(['vk_auth_key' => $token]);
        return static::findOne(['access_token' => $token]);

    }

    public function beforeSave($insert)
    {
 //       var_dump($this->access_token); exit;
        if (empty($this->access_token)) {
            $this->access_token = uniqid();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getFullList() {
        $models =  self::find()->all();
        return ArrayHelper::map($models,'id','username');
    }
}
